#+LaTeX_class: collab
#+TITLE: The Cross Curvature Flow, Einstein-Ricci Flow and Adjugate Einstein Flow

#+LaTeX_header: \input{setup}
* Introduction
* Notation and Conventions

Here we establish the basic notation and conventions used in this paper. These will be used freely throughout the paper without further mention.

** Algebraic Conventions

For a bilinear form \(B\), we define the transpose \(\tpose{B}\) of \(B\) by
\[
\tpose{B}(X, Y) = B(Y, X),
\]
the symmetrisation \(\Sym B\) of \(B\) by
\[
\Sym B(X, Y) = \frac{1}{2} \left[B(X, Y) + \tpose{B}(X, Y)\right] = \frac{1}{2} \left[B(X, Y) + B(Y, X),
\right]
\]
and the anti-symmetrisation \(\Alt B\) of \(B\) by
\[
\Alt B(X, Y) = \frac{1}{2} \left[B(X, Y) - \tpose{B}(X, Y)\right] = \frac{1}{2} \left[B(X, Y) - B(Y, X)\right].
\]
Then \(B\) is symmetric if and only if \(B = \Sym B\) if and only if \(\Alt B = 0\) while \(B\) is anti-symmetric if and only if \(B = \Alt B\) if and only if \(\Sym B = 0\).

We also define the \(g\)-representative endomorphism \(\edo{B}\) of \(B\) by
\[
B(X, Y) = g(\edo{B} (X), Y).
\]
The adjoint \(\adjt{T}\) of an endormophism \(T\) is defined by
\[
g(T(X), Y) = g(X, \adjt{T}(Y)),
\]
and \(T\) is \(g\)-self adjoint provided, \(\adjt{T} = T\). That is,
\[
g(T(X), Y) = g(X, T(Y)).
\]

Then \(B\) is symmetric if and only if \(\edo{B}\) is \(g\)-self adjoint. The adjoint and the transpose are related by
\[
\tpose{B} (X, Y) = B(Y, X) = g(\edo{B}(Y), X) = g(\adjt{\edo{B}} (X), Y)
\]
so that
\[
\adjt{\edo{B}} = \edo{\tpose{B}}
\]
where the notation let's us down a little here with the right hand side supposed to be the \(g\)-representative endomorphism for \(\tpose{B}\).

The self-adjoint endomorphism \(\Sym \edo{B}\) is defined by
\[
g(\Sym \edo{B} (X), Y) = \Sym B(X, Y)
\]
and the anti self-adjoint endomorphism \(\Alt \edo{B}\) is defined by
\[
g(\Alt \edo{B} (X), Y) = \Alt B(X, Y).
\]
Then since
\[
\frac{1}{2}\left[B(X, Y) + B(Y, X)\right] = \frac{1}{2} g(\edo{B}(X) + \adjt{\edo{B}}(X), Y)
\]
we have
\[
\Sym \edo{B} = \frac{1}{2} \left[\edo{B} + \adjt{\edo{B}}\right].
\]
Likewise,
\[
\Alt \edo{B} = \frac{1}{2} \left[\edo{B} - \adjt{\edo{B}}\right].
\]

We define the adjugate, \(\adjg{T}\) of an endomorphism \(T\) by
\[
\adjg{T} (X) \wedge \sigma = X \wedge \Lambda^{n-1} T(\sigma)
\]
where \(X\) is a tangent vector, \(\sigma \in \Lambda^{n-1} TM\) is an \(n-1\) vector and \(\Lambda^{n-1} T\) is defined on indecomposable \(n-1\) vectors by
\[
\Lambda^{n-1} T (X_1 \wedge \cdots \wedge X_{n-1}) = T(X_1) \wedge \cdots \wedge T(X_{n-1}).
\]
In other words, \(\adjg{T}\) is the adjoint of \(\Lambda^{n-1} T\) under the perfect pairing,
\[
X, \sigma \mapsto X \wedge \sigma.
\]
It satisfies,
\[
\adjg{T} \circ T = \det T \Id
\]
since
\[
\adjg{T} \circ T (X) \wedge \sigma = T(X) \wedge \Lambda^{n-1} T (\sigma) = \Lambda^n T (X \wedge \sigma) = \det T X \wedge \sigma.
\]
In particular, if \(T\) is invertible then
\[
\adjg{T} = \det T T^{-1}.
\]
The adjugate will be discussed in more detail in the next section.

We identify the alternating algebra with the image of the alternating map as a sub-algebra of the tensor algebra:
\[
X_1 \wedge \cdots \wedge X_k = \Alt (X_1 \otimes \cdots \otimes X_k) = \frac{1}{k!} \sum_{\sigma \in S_k} (-1)^{\text{sgn} \sigma} X_{\sigma_1} \otimes \cdots \otimes X_{\sigma_k}.
\]
For an inner product space, the induced inner product on tensors is defined by,
\[
g(X_1 \otimes \cdots \otimes X_k, Y_1 \otimes \cdots \otimes Y_k) = g(X_1, Y_1) \cdots g(X_k, Y_k)
\]
and on alternating tensors by
\[
g(X_1 \wedge \cdots \wedge X_k, Y_1 \wedge \cdots \wedge Y_k) = k! g(\Alt (X_1 \otimes \cdots \otimes X_k), \Alt (Y_1 \otimes \cdots \otimes Y_k)).
\]

In particular, for \(k=2\) we have
\[
X \wedge Y = \frac{1}{2}(X \otimes Y - Y \otimes X)
\]
and
\[
g(X \wedge Y, Z \wedge W) = g(X, Z) g(Y, W) - g(X, W) g(Y, Z)
\]
so that
\[
\abs{X \wedge Y}_g^2 = g(X \wedge Y, X \wedge Y) = |X|_g^2 |Y|_g^2 - g(X, Y)^2.
\]

Similarly we define the symmetric product,
\[
X_1 \odot \cdots \odot X_k = \Sym (X_1 \otimes \cdots \otimes X_k) = \frac{1}{k!} \sum_{\sigma \in S_k} X_{\sigma_1} \otimes \cdots \otimes X_{\sigma_k}
\]
and metric
\[
g(X_1 \odot \cdots \odot X_k, Y_1 \odot \cdots \odot Y_k) = k! g(\Sym (X_1 \otimes \cdots \otimes X_k), \Sym (Y_1 \otimes \cdots \otimes Y_k)).
\]

The Kulkarni-Nomizu product is defined for symmetric bilinear forms by
\begin{align*}
B \owedge C (X, Y, Z, W) &= B \owedge C (X \wedge Y, Z \wedge W) \\
&= \frac{1}{2} \big[B(X, Z) C(Y, W) - B(X, W) C(Y, Z) \\
&\quad + B(Y, W) C(X, Z) - B(Y, Z) C(X, W)\big].
\end{align*}

We can also define a Kulkarni-Nomizu product for endomorphisms,
\begin{align*}
T \owedge S (X, Y) &= T \owedge S (X \wedge Y) \\
&= \frac{1}{2} \big(T(X) \wedge S(Y) + S(X) \wedge T(Y)\big) \\
&= \frac{1}{4}\big(T(X) \otimes S(Y) - S(Y) \otimes T(X) + S(X) \otimes T(Y) - T(Y) \otimes S(X)\big).
\end{align*}
Then if \(B(X, Y) = g(T(X), Y)\) and \(C(X, Y) = g(S(X), Y)\) we have
\[
B \owedge C (X \wedge Y, Z \wedge W) = g(T \owedge S (X \wedge Y), Z \wedge W).
\]

Equivalently, both formulations arise by polarising the quadratic forms,
\[
T \mapsto T \wedge T, \quad T \wedge T(X \wedge Y) = T(X) \wedge T(Y)
\]
and
\[
B \mapsto B \wedge B, \quad B \wedge B (X \wedge Y, Z \wedge W) = B(X, Z) B(Y, W) - B(X, W) B(Y, Z)
\]
which also satisfy
\[
B \wedge B (X \wedge Y, Z \wedge W) = g(T \wedge T(X \wedge Y), Z \wedge W)
\]
whenever \(B(X, Y) = g(T(X), Y)\). From this perspective, it becomes clear why it's necessary to symmetrise \(T \wedge S\) in the definition of \(T \owedge S\) since polarising a quadratic form gives a symmetric form. Alternatively, without the symmetrisation, the map \(X, Y \mapsto T(X) \wedge S(Y)\) is not alternating so does not determine a map on \(X \wedge Y\). In other words, \(T \wedge S\) does not determine a map on \(X \wedge Y\).

So let us note explicitly the symmetry,
\[
B \owedge C = C \owedge B \quad, T \owedge S = S \owedge T.
\]

When \(B = C = g\) we have in particular,
\[
g(X \wedge Y, Z \wedge W) = g \owedge g (X \wedge Y, Z \wedge W)
\]
and hence
\[
\abs{X \wedge Y}_g^2 = g \owedge g(X \wedge Y, X \wedge Y).
\]

** Differential Geometric Conventions

For a Riemannian manifold \((M, g)\) we write \(\nabla\) for  the Levi-Civita connection. For a function \(f\) and a tangent vector, we write
\[
\partial_X f = df(X).
\]
Derivatives of tensors \(T\) will be written \(\nabla^k T\) so that for any \(k\) tangent vectors \(X_1, \cdots, X_k\) the contraction of \(\nabla^k T\) with \(X_1, \cdots, X_k\) written,
\[
\nabla^k_{X_1, \cdots, X_k} T
\]
is a tensor of the same type as \(T\). We also use the notation for contractions of such derivatives,
\[
\nabla^k_{X_1, \cdots, X_k} T (Y_1, \cdots, Y_p, \alpha^1, \cdots, \alpha^q)
\]
where \(T\) is a \((p, q)\) tensor in \(\otimes^p T^{\ast}M \bigotimes \otimes^q TM\). Sometimes we may also write
\[
\nabla^k_{X_1, \cdots, X_k} T (Y_1, \cdots, Y_p, \alpha^1, \cdots, \alpha^q) = \nabla^k T (X_1, \cdots, X_k; Y_1, \cdots, Y_p, \alpha^1, \cdots, \alpha^q).
\]

In particular, second derivatives will be written as follows: For a function \(f\),
\[
\nabla^2_{X, Y} f = \nabla^2 f (X, Y) = \partial_X (\partial_Y f) - \partial_{\nabla_X Y} f.
\]
For a vector field \(Z\),
\[
\nabla^2_{X, Y} Z = \nabla^2 Z (X, Y) = \nabla_X (\nabla_Y Z) - \nabla_{\nabla_X Y} Z.
\]
First derivatives of some higher tensors will be written:
For an endormorphism \(T\),
\[
\nabla_X T (Y) = \nabla T (X; Y) = \nabla_X (T(Y)) - T(\nabla_X Y).
\]
For a bilinear form \(\alpha\) on \(TM\),
\[
\nabla_X \alpha (Y, Z) = \nabla \alpha(X; Y, Z) =  \partial_X (T(Y, Z)) - T(\nabla_X Y, Z) - T(Y, \nabla_X Z).
\]

Then for example, we express metric compatibility \(\nabla_X g = 0\) by
\[
\partial_X g(Y, Z) = g(\nabla_X Y, Z) + g(Y, \nabla_X Z).
\]

Our conventions for the curvature tensor are
\[
\Rm(X, Y) Z = \nabla_X (\nabla_Y Z) - \nabla_Y (\nabla_X Z) - \nabla_{[X, Y]} Z
\]
from which immediately follows the Ricci identity,
\[
\Rm(X, Y) Z = \nabla^2_{X, Y} Z - \nabla^2_{Y, X} Z
\]
since the Levi-Civita connection is torsion free and hence \(\nabla_X Y - \nabla_Y X = [X, Y]\). The metric contracted curvature tensor will be written,
\[
\Rm(X, Y, Z, W) = g(\Rm(X, Y) Z, W).
\]
Then we have the sectional curvature,
\[
\K(X \wedge Y) = \frac{\Rm(X, Y, Y, X)}{\abs{X \wedge Y}_g^2}.
\]
Thus a metric \(g\) of constant sectional curvature \(K\) satisfies,
\[
\Rm(X, Y, Z, W) = -K g \owedge g (X, Y, Z, W) = -K [g(X, Z) g(Y, W) - g(X, W) g(Y, Z)]
\]
where \(\owedge\) denotes the Kulkarni-Nomizu product.

The Ricci curvature is the symmetric, bilinear form,
\[
\Ric(X, Y) = \Tr Z \mapsto \Rm(Z, X) Y.
\]
The scalar curvature, \(\Sc\) is obtained by tracing:
\[
\Sc = \Tr \edoRic
\]
where \(\edoRic\) is the self adjoint endomorphism representing \(\Ric\), defined above by
\[
\Ric(X, Y) = g(\edoRic (X), Y).
\]
The trace free Ricci tensor is
\[
\Trfree{\Ric} = \Ric - \frac{\Sc}{n} g
\]
with representing endomorphism,
\[
\edoTrfreeRic = \edoRic - \frac{\Sc}{n} \Id.
\]
In terms of the \((4, 0)\) curvature tensor, we may also write,
\[
\Ric(X, Y) = \Tr_g \Rm(\cdot, X, Y, \cdot)
\]
where for a bilinear form, \(B\), we define
\[
\Tr_g B = \Tr \edo{B} = g(B, g).
\]
This also gives
\[
\Sc = \Tr_g \Ric.
\]

The Ricci decomposition of the \((4, 0)\) curvature tensor is
\[
\Rm = -g \owedge \schouten + \weyl = -\frac{R}{n(n-1)} g \owedge g - \frac{2}{n-2} g \owedge \Trfree{\Ric} + \weyl
\]
where
\[
\weyl = \Rm + g \owedge P
\]
is the Weyl tensor and
\[
\schouten = \frac{2}{n-2} \Trfree{\Ric} + \frac{R}{n(n-1)} g  = \frac{2}{n-2}\left(\Ric - \frac{R}{n-1} g\right).
\]
is the Schouten tensor. A nice way to motivate \(\weyl\) and \(\schouten\) is to observe that if we define for a curvature-like tensor \(K\),
\[
c(K) (X, Y) = \Tr_g K(\cdot, X, Y, \cdot)
\]
then, \(c\) is the \(g\) adjoint of the map \(B \mapsto \frac{1}{2} g \owedge B\) for a \(B\) a bilinear form. That is,
\[
g(c(K), B) = g(K, \frac{1}{2} g \owedge B).
\]
Moreover,
\[
c(\frac{1}{2} g \owedge B) = (n-2) B + \Tr_g (B) g.
\]
Applying this to \(B = \Ric\) gives,
\[
P = c(\frac{1}{2} g \owedge \Ric)
\]
and the Weyl tensor \(\weyl\) contains the most complexity of \(\Rm\) - ie. that part not arising from the indecomposable element \(-g \owedge P\) built from the Ricci tensor \(\Ric = c(\Rm)\). Let us also note that in dimensions \(n = 1,2,3\), \(\weyl \equiv 0\) while in dimensions \(n \geq 4\), \(\weyl \equiv 0\) if and only if \((M, g)\) is locally conformally flat.

In particular, in dimensions \(n = 2, 3\), \(\Rm = -g \owedge \schouten\) so \(\Rm\) is a much simpler object. The Ricci decomposition as written is only valid when \(n > 2\), but when \(n = 2\), \(\Trfree{\Ric} \equiv 0\) and so if we make the convention \(\tfrac{1}{n-2} \Trfree{\Ric} = 0\) for \(n = 2\), the decomposition holds. In dimension \(n = 4\), the Weyl tensor decomposes further as \(\weyl = \weyl^+ + \weyl^-\) into self-dual and anti-self dual parts. For \(n > 5\) it is indecomposable under the action of \(O(n)\). Let us record explicitly,
\begin{align*}
\Rm & = -\frac{R}{2} g \owedge g, \quad n = 2, \\
\Rm & = -\frac{R}{6} g \owedge g - 2 g \owedge \Trfree{\Ric}, \quad n = 3, \\
\Rm &= -\frac{R}{12} g \owedge g - g \owedge \Trfree{\Ric} + \weyl^+ + \weyl^-, \quad n = 4.
\end{align*}

The Einstein gravitation tensor, \(\Ein\) is the symmetric bilinear form,
\[
\Ein(X, Y) = \Ric(X, Y) - \frac{\Sc}{2} g(X, Y).
\]
It's \(g\) representative endomorphism, \(\edoEin\) satisfies
\[
\edoEin = \edoRic - \frac{\Sc}{2} \Id
\]
where \(\Id\) is the identity endomorphism.

Now we introduce two new tensors that will be used to define our flows. They will be discussed in more detail in the following sections.

#+BEGIN_defn
\label{defn:ricci_einstien}
The Ricci-Einstein tensor, \(\RicEin\) is defined by
\[
\RicEin(X, Y) = \Tr Z \mapsto \Rm(\edoEin(Z), X) Y
\]
with associated endomorphism, \(\edoRicEin\) satisfying
\[
\RicEin(X, Y) = g(\edoRicEin(X), Y).
\]
#+END_defn

#+BEGIN_defn
\label{defn:adjugate_einstien}
The adjugate Einstein tensor,
\[
\adjg{\Ein} (X, Y) = g(\adjg{\edoEin} (X), Y).
\]
#+END_defn

* Definition of the Flows

** Ricci-Einstein and Adjugate Einstein Differential Operators

Recall the definition \ref{defn:ricci_einstien}
\[
\RicEin(X, Y) = \Tr Z \mapsto \Rm(\edoEin(Z), X) Y
\]
and definition \ref{defn:adjugate_einstien},
\[
\adjg{\Ein} (X, Y) = g(\adjg{\edoEin} (X), Y).
\]
These are degenerate differential operators (acting on \(g\)) unless the sectional curvature has a sign. Thus let us write,
\begin{equation}
\label{eq:K_sign}
\sK = \begin{cases}
1, & \K > 0, \\
-1, & \K < 0.
\end{cases}
\end{equation}
Thus we express that \(\K > 0\) /or/ \(\K < 0\) by the single inequality
\[
\sK\K > 0.
\]

Since these operators are geometric, they are diffeomorphism invariant and thus have zero's in the principal symbols corresponding to these tangential directions hence they can be at best only weakly elliptic. As is well known however, by applying the technique of DeTurck \cite{} this degeneracy can be removed by a suitable choice of diffeomorphism. With this in mind, let us make the following definition:

#+BEGIN_defn
A differential operator \(D : E \to F\) between vector bundles \(E, F\) over a base manifold \(M\) is (strictly) /geometrically elliptic/ if
1. \(D\) is diffeomorphism invariant; that is for every section \(s \in \Gamma(E)\) and every diffemorphism \(\varphi : M \to M\), \(D(\varphi^{\ast} s) = \varphi^{\ast} D (s)\), and
2. up to diffeomorphism, \(D\) is elliptic; that is for each smooth section \(s \in \Gamma(E)\), there exists a diffeomorphism \(\varphi : M \to M\) such that
   \[
   \psym[D'(\varphi^{\ast} s)] \geq \lambda > 0
   \]
   where \(D'(\varphi^{\ast} s) (\xi) = \partial_u|_{u=0} D(\varphi^{\ast} s + u\xi)\) denotes the linearisation of \(D\) at \(\varphi^{\ast} s\) and \(\psym\) denotes the principal symbol.
#+END_defn

Before showing the ellipticity of \(\RicEin\) and \(\adjg{\Ein}\), let us show that both these tensors are symmetric. Recall that if \(u \mapsto g_u\) is a curve of metrics, then \(\partial_u g_u (X, Y) := \partial_u [g_u (X, Y)]\) is a symmetric bilinear form and conversely that if \(B\) is any field of symmetric bilinear forms, for sufficiently small \(u\), \(g + uB\) is a positive definite symmetric bilinear form hence a metric. Here we use the fact that \(M\) is compact and thus the unit tangent bundle \(UM = \{X \in TM : g(X, X) = 1\}\) is compact to ensure \(g_x + uB_x\) is positive definite uniformly in \(x\). That is there is an \(\epsilon > 0\) independent of \(x\) such that for all \(x\), \(g_x + uB_x\) is positive definite for all \(u \in (-\epsilon, \epsilon)\). Thus we may identify the tangent space to the space of metrics with the bundle \(T^{\ast} M \odot T^{\ast} M\) of symmetric bilinear forms acting on \(TM\). The following two lemmas then show that \(\RicEin\) and \(\adjg{\Ein}\) are in this tangent space.

#+BEGIN_lemma
\label{lem:EinRicsym}
The Ricci-Einstien tensor is symmetric. That is, for all tangent vectors \(X, Y \in TM\) with \(\pi_{TM} (X) = \pi_{TM} (Y)\) we have
\[
\RicEin (X, Y) = \RicEin (Y, X).
\]
#+END_lemma

#+BEGIN_proof

#+END_proof

#+BEGIN_lemma
\label{lem:EinRicsym}
The adjugate Einstien tensor is symmetric. That is, for all tangent vectors \(X, Y \in TM\) with \(\pi_{TM} (X) = \pi_{TM} (Y)\) we have
\[
\adjg{\Ein} (X, Y) = \adjg{\Ein} (Y, X).
\]
#+END_lemma

#+BEGIN_proof

#+END_proof

#+BEGIN_thm
On the open set of all metrics \(g\) satisfying \(\sK\K > 0\), the (signed) Ricci-Einstien tensor \(-\sK \RicEin\) is geometrically elliptic.
#+END_thm

#+BEGIN_thm
On the open set of all metrics \(g\) satisfying \(\sK\K > 0\), the (signed) adjugate Einstien tensor \(-\sK \adjg{\Ein}\) is geometrically elliptic.
#+END_thm

** The flows

Here we let \(g_t\) be a smooth, one-parameter family of metrics.

#+BEGIN_defn
The family \(g_t\) satisfies the /Ricci Einstein flow/ provided
\[
\partial_t g_t = -\frac{1}{2} \sK \RicEin.
\]
#+END_defn

#+BEGIN_defn
The family \(g_t\) satisfies the /adjugate Einstein flow/ provided
\[
\partial_t g_t = -\frac{1}{2} \sK \adjg{\Ein}.
\]
#+END_defn

#+BEGIN_rem
In dimension, \(n = 3\) in fact, \(\RicEin = \adjg{\Ein}\) and the common flow is known as the /cross curvature flow/. See section \ref{sec:xcf3} for details.
#+END_rem

* Short Time Existence and Uniqueness
* Evolution Equations
* Cross Curvature Flow of Three Manifolds
\label{sec:xcf3}

* Vanishing Weyl in Higher Dimensions
* Embeddability and Integrability
* Solitons
* The Harnack Inequality
* Entropy
* Convergence
* Coordinate Notation                                              :noexport:
The Riemannian metric is $g_{ij}$, its inverse is $g^{ij}$. The Levi-Civita connection is given by the Christoffel symbols
\begin{equation}
\Gamma_{ij}^k=\frac{1}{2}g^{kl}\left(\partial_ig_{jl}+\partial_jg_{il}-\partial_lg_{ij}\right).
\end{equation}
Write $\nabla^2_{i,j}$ for the second covariant derivative; for any tensor $\alpha:$
\[\nabla^2_{i,j}\alpha=\nabla_{\partial_i}\nabla_{\partial_j}\alpha-\nabla_{\nabla_{\partial_i}\partial_j}\alpha.\]
The Riemannian curvature tensor is
\begin{equation}
R_{ijk}^l=\partial_i\Gamma_{jk}^l-\partial_j\Gamma_{ik}^l+\Gamma_{jk}^p\Gamma_{ip}^l-\Gamma_{ik}^p\Gamma_{jp}^l.
\end{equation}
We lower the index to the third position, so that
\begin{equation}
R_{ijkl}=g_{kp}R_{ijl}^p.
\end{equation}
The Ricci curvature is the contraction
\begin{equation}
R_{ij}=g^{kl}R_{ikjl}.
\end{equation}
The scalar curvature $R=g^{ij}R_{ij}$.


The evolution equation of the metric is given by
\begin{equation}
\partial_tg_{ij}=2h_{ij},
\end{equation}
where
\begin{equation}
h_{ij}:=-\frac{1}{2}P^{kl}R_{ikjl}
\end{equation}
and
\begin{equation}
P_{ij}:=R_{ij}-\frac{1}{2}Rg_{ij},\quad
P^{mn}=\left(R_{ij}-\frac{1}{2}Rg_{ij}\right)g^{im}g^{jn}.
\end{equation}
Let $V_{ij}$ be the inverse of $P^{ij}$. We mention that
\begin{equation}
h_{ij}=V_{ij}\det P,
\end{equation}
where $\det P = \det (g_{km} P^{ml})$.

We also write
\begin{align}
P&=g_{ij}P^{ij},\quad V=g^{ij}V_{ij},\quad H=g^{ij}h_{ij},\quad u:=\log\det P\\
T^{kij}&=P^{kl}\nabla_l P^{ij},\quad T^i=V_{jk}T^{ijk}=P^{ij}\nabla_ju.
\end{align}

\begin{note}
We use
\[
\nabla_l \det P = (V^i_j \nabla_l P^{jk} g_{ik}) \det P = V_{ij} \nabla_l P^{ij} \det P = h_{ij} \nabla_l P^{ij}
\]
to get
\[
T^i = V_{jk}T^{ijk} = V_{jk} P^{il}\nabla_l P^{jk} = \frac{1}{\det P} P^{il} h_{jk} \nabla_l P^{jk} = \frac{1}{\det P} P^{il} \nabla_l \det P = P^{il} \nabla_l u.
\]

It's also worth noting that \(T^{kij} = T^{kji}\).
\end{note}

In the sequel, $\mu_{ijk}$ is the volume form and is nonzero only when $i,j,k$ are distinct, in which case it is sign of the permutation $(ijk)$. Using the volume form, we may express $P^{mn}$ as
\begin{equation}
P^{mn}=-\frac{1}{4}\mu^{ijm}\mu^{kln}R_{ijkl}.
\end{equation}
We conclude this section by scatting the following identities from \cite[Lemma 1]{MR2055396}:
\begin{align}\label{equ: important}
P^{ij}\nabla_ih_{jk}&=\frac{1}{2}P^{ij}\nabla_kh_{ij},\quad
\nabla_iP^{ij}=0.
\end{align}

* Solitons                                                         :noexport:

A solution to cross curvature flow is a cross curvature soliton if there exists a vector field $W$ and $\lambda\in \mathbb{R}$ such that at some time
\begin{equation}\label{soliton 0}
2\lambda g_{ij}=2h_{ij}+\nabla_iW_j+\nabla_jW_i.
\end{equation}
For an expanding soliton, (\ref{soliton 0}) holds with $\lambda=\frac{1}{4t}$. To obtain a suitable Harnack quadratic for XCF, we follow Hamilton's procedure in obtaining his trace Harnack quantity for the Ricci flow.


We take the covariant derivative of both sides of (\ref{soliton 0}) with respect to $\nabla_l:$
\begin{align}\label{eq: soliton derv}
2\nabla_lh_{ij}+\nabla^2_{l,i}W_j+\nabla^2_{l,j}W_i=0.
\end{align}
We also take the trace of (\ref{soliton 0}) with respect to $P^{ij}$:
\begin{align}\label{trace}
\lambda P=3\det P+P^{ij}\nabla_iW_j.
\end{align}
Taking the covariant derivative of both sides with respect to $\nabla_l$ yields
\begin{align*}
\lambda \nabla_l P=3\nabla_l\det P+\nabla_l P^{ij}\nabla_iW_j+P^{ij}\nabla^2_{l,i}W_j.
\end{align*}
In view of
\begin{align*}
\nabla^2_{l,i}W_j-\nabla^2_{i,l}W_j=R_{lijk} g^{km}W_m,
\end{align*}
we obtain
\begin{align}\label{equ00}
\lambda \nabla_l P&=3\nabla_l\det P+\nabla_l P^{ij}\nabla_iW_j+P^{ij}(\nabla^2_{i,l}W_j -R_{likj}g^{km}W_m)\\
&=3\nabla_l\det P+\nabla_l P^{ij}\nabla_iW_j+P^{ij}\nabla^2_{i,l}W_j+2h_l^mW_m.\nonumber
\end{align}
For now on  we consider gradient solitons which are by definition, when $W_i=\nabla_if$ for a smooth function (note that in this case $\nabla_iW_j=\nabla_jW_i$).
Putting (\ref{soliton 0}), (\ref{eq: soliton derv}) together we obtain
\begin{align}\label{eq:1}
\lambda \nabla_l P
=&3\nabla_l\det P+(\lambda g_{ij}-h_{ij})\nabla_l P^{ij}-P^{ij}\nabla_ih_{jl}+2h_l^mW_m\\
=&3\nabla_l\det P+\lambda \nabla_l P-h_{ij}\nabla_l P^{ij}-\frac{1}{2}P^{ij}\nabla_lh_{ij}+2h_l^mW_m.\nonumber
\end{align}
We may rewrite (\ref{eq:1}) as
\[3\nabla_l\det P+2h_l^mW_m-h_{ij}\nabla_l P^{ij}-\frac{1}{2}P^{ij}\nabla_lh_{ij}=0.\]
We divide both sides by $\det P:$
\begin{equation}\label{eq:a}
\nabla_lu+\frac{2}{\det P}h_l^mW_m=0,
\end{equation}
where we used
\begin{equation}\label{eq0}
\frac{P^{ij}}{\det P}\nabla_lh_{ij}=2\nabla_lu,\quad V_{ij}\nabla_lP^{ij}=\nabla_lu.
\end{equation}

\begin{note}
\[
\nabla_l \det P = (V^i_j \nabla_l P^{jk} g_{ik}) \det P = V_{ij} \nabla_l P^{ij} \det P = h_{ij} \nabla_l P^{ij}
\]
\end{note}

Taking the covariant derivative of (\ref{eq:a}) with respect to $\nabla_k$ and then using the first soliton equation (\ref{soliton 0}) yields
\begin{equation*}
\nabla^2_{k,l}u+\frac{2}{\det P}\nabla_kh_l^mW_m-\frac{2}{\det P}h_l^mW_m\nabla_ku-2V_l^mh_{km}+2\lambda V_{kl}=0.
\end{equation*}
We take the trace with respect to $P^{kl}$ and use the first identity in (\ref{eq0}):
\begin{equation}\label{eq:5}
\Box u-2H+6\lambda=0.
\end{equation}

\begin{note}
We can derive most of the soliton equations for general solitons, not just restricted to gradient solitons.

Recall equation (2.1):
\[
2\lambda g_{ij}=2h_{ij}+\nabla_iW_j+\nabla_jW_i.
\]
and equation (2.2):
\[
2\nabla_lh_{ij}+\nabla^2_{l,i}W_j+\nabla^2_{l,j}W_i=0.
\]
Rewrite (2.3) as
\[
\lambda P = 3 \det P + \frac{1}{2}P^{ij} \left(\nabla_i W_j + \nabla_j W_i\right).
\]
Then differentiating, the new (2.4) becomes,
\[
\lambda \nabla_l P = 3 \nabla_l \det P + \frac{1}{2}\nabla_l P^{ij} \left(\nabla_i W_j + \nabla_j W_i\right) + \frac{1}{2} P^{ij} \left(\nabla^2_{l,i} W_j + \nabla^2_{l,j} W_i\right)
\]

Apply (2.1) to the second term above, and (2.2) to the third term to obtain a new (2.5):
\[
\lambda \nabla_l P = 3 \nabla_l \det P + \lambda \nabla_l P - \nabla_l P^{ij}h_{ij} - P^{ij} \nabla_l h_{ij}.
\]

We may rewrite this new (2.5) as
\[
3 \nabla_l \det P - h_{ij} \nabla_l P^{ij} - P^{ij} \nabla_l h_{ij} = 0 
\]

Dividing by \(\det P\) we obtain the trivial identity
\begin{align*}
0 &= 3 \nabla_l u - \frac{1}{\det P} h_{ij} \nabla_l P^{ij} - \frac{1}{\det P} P^{ij} \nabla_l h_{ij} \\
&= 0.
\end{align*}
In the second line we used (2.7):
\[
\nabla_l \det P = (V^i_j \nabla_l P^{jk} g_{ik}) \det P = V_{ij} \nabla_l P^{ij} \det P = h_{ij} \nabla_l P^{ij}
\]
for the second term, and
\begin{align*}
P^{ij} \nabla_l h_{ij} &= \det P P^{ij} \nabla_l V_{ij} + P^{ij} V_{ij} \nabla_l \det P \\
&= -\det P V_{ij} \nabla_l P^{ij} + 3 \nabla_l \det P \\
&= 2 \nabla_l \det P
\end{align*}
for the third term.

So, to get anything non-trivial, we go back to the new (2.4) and apply the Ricci identity,
\[
\nabla^2_{l,i} W_j = \nabla^2_{i,l} W_j + R_{lijk} g^{km} W_m
\]
to write
\begin{align*}
\frac{1}{2} P^{ij} \left(\nabla^2_{l,i} W_j + \nabla^2_{l,j} W_i\right) &= \frac{1}{2} P^{ij} \left(\nabla^2_{i,l} W_j + \nabla^2_{j,l} W_i\right) + \frac{1}{2} P^{ij} \left(R_{lijk} + R_{ljik}\right) g^{km}W_m \\
&= \frac{1}{2} P^{ij} \left(\nabla^2_{i,l} W_j + \nabla^2_{j,l} W_i\right) - \frac{1}{2} P^{ij} \left(R_{iljk} + R_{jlik}\right) g^{km}W_m \\
&= \frac{1}{2} P^{ij} \left(\nabla^2_{i,l} W_j + \nabla^2_{j,l} W_i\right) + 2 h_{kl} g^{km} W_m
\end{align*}
Then our (2.5) becomes,
\[
3 \nabla_l \det P + 2 h_l^m W_m - \nabla_l P^{ij}h_{ij} + \frac{1}{2} P^{ij} \left(\nabla^2_{i,l} W_j + \nabla^2_{j,l} W_i\right) = 0
\]
Dividing by \(\det P\) and using (2.7) we get the new (2.6),
\[
2 \nabla_l \det u + \frac{2}{\det P} h_l^m W_m + \frac{1}{2\det P} P^{ij} \left(\nabla^2_{i,l} W_j + \nabla^2_{j,l} W_i\right) = 0
\]

Now we get a little stuck because we can't apply (2.2) to the last term. If we had a symmetric vector field (\(\nabla_i W_j = \nabla_j W_i\)) - in particular if \(W = \operatorname{grad} f\) - then we could write (2.2) as
\[
\nabla^2_{l,i} W_j = -\nabla_l h_{ij}.
\]
Then we would do as in the paper,
\begin{align*}
\frac{1}{2} P^{ij} \left(\nabla^2_{l,i} W_j + \nabla^2_{l,j} W_i\right) &= P^{ij} \nabla^2_{l,i} W_j \\
&= P^{ij} \nabla^2_{i,l} W_j + 2 h_{kl} g^{km} W_m \\
&= -P^{ij} \nabla_i h_{lj} + 2 h_{kl} g^{km} W_m \\
&= -\frac{1}{2} P^{ij} \nabla_l h_{ij} + 2 h_l^m W_m.
\end{align*}
In other words,
\[
\frac{1}{2} P^{ij} \left(\nabla^2_{i,l} W_j + \nabla^2_{j,l} W_i\right)  = - \frac{1}{2} P^{ij} \nabla_l h_{ij} = - \nabla_l \det P
\]
for gradient solitons after also using (2.7). Putting this in the new (2.6) above, we get the same (2.6) as in the paper,
\[
\nabla_l u + \frac{2}{\det P} h_l^m W_m = 0.
\]

Differentiate with respect \(k\):
\[
0 = \nabla^2_{k,l} u + \frac{2}{\det P} \nabla_k h_l^m W_m + \frac{2}{\det P} h_l^m \nabla_k W_m - h_l^m W_m \frac{2}{(\det P)^2} \nabla_k \det P
\]
Using (2.1) the second term is
\[
\frac{2}{\det P} h_l^m \nabla_k W_m =  \frac{2}{\det P} h_l^m \left(\lambda g_{km} - h_{km}\right) = 2 \lambda V_{kl} - 2 V_{km} h_l^m.
\]
The third term is
\[
h_l^m W_m \frac{2}{(\det P)^2} \nabla_k \det P = \frac{2}{\det P} h_l^m W_m \nabla_k u.
\]

Thus we get
\[
0 = \nabla^2_{k,l} u + \frac{2}{\det P} \left(\nabla_k h_l^m  - h_l^m \nabla_k u\right) W_m + 2 \lambda V_{kl} - 2 V_{km} h_l^m.
\]
Tracing with respect to \(P^{kl}\) gives
\[
\begin{split}
P^{kl} h_l^m \nabla_k u &= P^{kl} h_l^m \frac{2}{\det P} P^{ij} \nabla_k h_{ij} \\
&= g^{sm} P^{kl} \det P V_{ls} \frac{2}{\det P} P^{ij} \nabla_k h_{ij} \\
&= 2 g^{km} P^{ij} \nabla_k h_{ij} \\
&= g^{km} P^{ij} \nabla_i h_{jk} \\
&= P^{ij} \nabla_i h_j^m
\end{split}
\]
which cancels with \(P^{kl} \nabla_k h_l^m\). For the last term,
\[
P^{kl} V_{km} h_l^m = \delta^l_m g^{ms} h_{ls} = g^{ms} h_{ms} = H.
\]

Thus we get (2.8),
\[
\Box u - 2 H + 6 \lambda = 0.
\]
\end{note}

# We take the trace with respect to $P^{kl}:$
# \begin{equation}\label{eq:4}
# \Box u+P^{kl}\nabla_ku\nabla_lu+2\nabla_kuV^k-2H+6\lambda=0.
# \end{equation}
# On the other hand, there holds
# \begin{align}\label{first derv test}
# \nabla^mh_{ij}-\nabla_jh_i^m={{{R_j}^{m}}_{i}}^nV_n\Rightarrow 4V_{kl}V^kV^l+2\nabla_kuV^k=0.
# \end{align}
# Hence adding (\ref{first derv test}) to (\ref{eq:4}) implies that
# \begin{align}\label{harnack quant}
# \Box u+4\left|V^i+\frac{1}{2}P^{ij}\nabla_ju\right|_{V_{kl}}^2
# -2H+6\lambda=0.
# \end{align}
So Lemma \ref{ev u} proposes the following candidate as the  Harnack inequality:
 \begin{align}\label{harnack est}
\partial_tu-\frac{1}{2}\left(\left|E^{ijk}-E^{jik}\right|^2_V+\left|T^i\right|_V^2\right)+\frac{3}{2t}\geq 0,
\end{align}
 where
 \[T^{ijk}=E^{ijk}-\frac{1}{10}\left(P^{ij}T^k+P^{ik}T^j\right)+\frac{2}{5}P^{jk}T^i,\]

\begin{note}
Since \(T\) is symmetric in the last two indices and the non-\(E\) terms on the right hand side also have this symmetry, \(E\) is symmetric in the last two indices.

The second relation below is not in Prop 9, but on p.6. The first one does not appear to be in the reference at all! That follows by,
\[
T^{ijk} V_{ij} = V_{ij} P^{il} \nabla_l P^{jk} = \nabla_j P^{jk} = 0.
\]
\end{note}

 and we have $T^{ijk}V_{ij}=0$, $V_{ij}E^{ijk}=V_{ik}E^{ijk}=V_{jk}E^{ijk}=0;$ see \cite[Prop. 9]{MR2055396}. In the case of embeddability into Minkowski 4-space, we have
 \begin{align*}
\left|E^{ijk}-E^{jik}\right|^2_V=0,\quad\frac{1}{2}\left|T^i\right|_V^2=\frac{1}{2}P^{ij}\nabla_i u\nabla_ju.
 \end{align*}
In fact, $E^{ijk}=E^{jik}$ due to the Codazzi equation which yields the full symmetry of the covariant derivative of the second fundamental form. In general, if 
$\alpha_{ij}:=\sqrt{\det P}V_{ij}$ satisfies
$\nabla_k\alpha_{ij}=\nabla_i\alpha_{jk}$,
then \[E^{ijk}=E^{jik}.\]
\begin{thm}
Let $(M^3,g(t))$, $t\in [0,T)$, be a solution to the XCF on a closed 3-manifold starting from a metric $g(0)$ with negative sectional curvature. Then $g(t)$ has negative sectional curvature for all $t<T.$
Moreover, it is not possible that $T<\infty$ and $\inf_{M\times [0,T)}\det P=0.$
\end{thm}
\begin{proof}
Suppose $0<t_{\ast}<T$ is the first time that $g(t_{\ast})$ has a zero sectional curvature at some point $x_{\ast}$. At $(x_{\ast},t_{\ast})$ we must have $\det P(x_{\ast},t_{\ast})=0.$
By our Harnack inequality, we know that $t^{\frac{3}{2}}\det P(\cdot,t) $ is increasing in time on $(0,t_{\ast})$; therefore, for any $t\in [t_{\ast}/2, t_{\ast})$ we have
\[\det P(\cdot,t)\geq \det P(\cdot,t_{\ast}/2)\left(\frac{1}{2}\right)^{\frac{3}{2}}>0.\]
Thus by continuity of the solution we obtain $\det P(\cdot,t_{\ast})>0$, which yields a contradiction.

\begin{note}
We have
\[
\partial_t (t^{3/2} \det P) = t^{3/2}\left(\partial_t \det P + \frac{3}{2t} \det P\right) = t^{3/2} \det P\left(\partial_t u + \frac{3}{2t}\right) \geq 0
\]
by the Harnack inequality and since \(\det P \geq 0\) for \(t \in (0, t_{\ast})\).
\end{note}

By the first part of the theorem, $P^{ij}$ is invertible on $[t_1,t_2]$ for any $t_1,t_2$ with $0<t_1\leq t_2<T.$ Thus the Harnack inequality is available on $[t_1,t_2]$ and it gives
\[\det P(\cdot,t_2)\geq \det P(\cdot,t_1)\left(\frac{t_1}{t_2}\right)^{\frac{3}{2}}.\]
Allowing $t_2\to T$ completes the proof.
\end{proof}
Before moving on to the proof of Harnack inequality, we give a classification of compact solitons of XCF with negative sectional curvatures.

\begin{thm}
The only compact solitons of XCF with negative sectional curvature are metrics with constant negative curvature.
\end{thm}

\begin{proof}
Apply (\ref{soliton 0}) to (\ref{equ00}):
\begin{align*}
\lambda \nabla_l P&=3\nabla_l\det P+(\lambda g_{ij}-h_{ij})\nabla_l P^{ij}+P^{ij}\nabla^2_{i,l}W_j+2h_l^mW_m\\
&=3\nabla_l\det P+\lambda \nabla_l P-h_{ij}\nabla_l P^{ij}+P^{ij}(-2\nabla_ih_{lj}-\nabla^2_{i,j}W_l)+2h_l^mW_m.
\end{align*}
Dividing both sides by $\det P$ implies that
\begin{align*}
3\nabla_lu-V_{ij}\nabla_l P^{ij}-\frac{P^{ij}}{\det P}\nabla_lh_{ij}-\frac{1}{\det P}(\Box W_l-2h_l^kW_k)=0.
\end{align*}
Therefore, by (\ref{eq0}) we obtain
\begin{align*}
\Box W_l-2h_l^kW_k=0\Rightarrow W^l\Box W_l-2h_l^kW_kW^l=0.
\end{align*}
The second identity reads
\begin{align}\label{soliton equation for W}
\Box \frac{1}{2}|W|_g^2-P^{kl}g^{ij}\nabla_kW_i\nabla_lW_j-2h^{kl}W_kW_l=0.
\end{align}

\begin{note}
The product rule for \(\Box\) gives,
\[
\frac{1}{2}\Box |W|_g^2 = \frac{1}{2} \Box(g^{ij} W_i W_j) = g^{ij} W_j \Box W_i + P^{kl} g^{ij} \nabla_k W_i \nabla_l W_j.
\]
Then,
\[
\begin{split}
\Box \frac{1}{2}|W|_g^2 - P^{kl}g^{ij}\nabla_kW_i\nabla_lW_j - 2h^{kl}W_kW_l &= g^{ij} W_j \Box W_i - 2 h^{kl}W_k W_l \\
&= W^i \Box W_i - 2 g^{il} h^k_i W_k g_{lj} W^j \\
&= W^i \Box W_i - 2 h^k_i W_k W^i = 0.
\end{split}
\]
\end{note}

Note that, by (\ref{equ: important}), $\int \Box fd\mu_{M}=0$ for any smooth function $f$ defined on $M$. Thus integrating (\ref{soliton equation for W}) against $d\mu_{M}$ and taking into account that $P_{ij}$ and $h_{ij}$ are both positive definite proves that $W\equiv0$ (also note that $g,P$ and $h$ can all be diagonalized simultaneously at any fixed point); therefore, by (\ref{soliton 0}), we get
\[(\det P)^2=\det h_{ij}=\lambda ^3\Rightarrow \det P=\lambda^{\frac{3}{2}}.\]

\begin{note}
\ref{soliton 0} says that for \(W = 0\), \(\lambda g_{ij} = h_{ij}\). Then,
\[
\det h = \det (g^{km} h_{ml}) = \det (g^{km} \det P V_{mk}) = (\det P)^3 \det V = \det P
\]
since \(V=P^{-1}\). On the other hand,
\[
\det h = \det \lambda g = \det (\lambda g^{km} g_{ml}) = \lambda^3.
\]
\end{note}

Moreover, in view of (\ref{trace}), we have $3\det P=\lambda P$; therefore, we obtain $$3(\det P)^{\frac{1}{3}}=P.$$ Thus the metric has constant negative curvature.
\begin{note}
This follows from Chow-Hamilton section 5 by diagonalising and applying the arithmetic-geometric mean inequality.
\end{note}
\end{proof}

* Evolution equations                                              :noexport:

We first collect a few identities that will be used without further mention:
\begin{align}\label{equ: important1}
P^{ij}\nabla_ih_{jk}&=\frac{1}{2}P^{ij}\nabla_kh_{ij},\quad
\nabla_iP^{ij}=0,\quad \nabla_iT^i=\Box u,\\
T^k\nabla_kP^{ij}&=T^{kij}\nabla_ku,\quad P^{ij}\nabla_j T^k=P^{ij}P^{kl}\nabla^2_{j,l}u+T^{ikl}\nabla_lu,\\
T^{ijk}-T^{jik}&=E^{ijk}-E^{jik}+\frac{1}{2}\left(P^{jk}T^i-P^{ik}T^j\right).
\end{align}

\begin{note}
\begin{align*}
P&=g_{ij}P^{ij},\quad V=g^{ij}V_{ij},\quad H=g^{ij}h_{ij},\quad u:=\log\det P\\
T^{kij}&=P^{kl}\nabla_l P^{ij},\quad T^i=V_{jk}T^{ijk}=P^{ij}\nabla_ju.
\end{align*}
\[
T^{ijk}=E^{ijk}-\frac{1}{10}\left(P^{ij}T^k+P^{ik}T^j\right)+\frac{2}{5}P^{jk}T^i,
\]
and we have $T^{ijk}V_{ij}=0$, $V_{ij}E^{ijk}=V_{ik}E^{ijk}=V_{jk}E^{ijk}=0$ (from Chow-Hamilton).
\end{note}

For simplicity, write
\[D^{ijk}=E^{ijk}-E^{jik}.\]
The tensor $D^{ijk}$ satisfies
\begin{align*}
D^{ijk}=-D^{jik},\quad D^{ijk}+D^{kij}+D^{jki}=0.
\end{align*}

\begin{note}
\[
\begin{split}
D^{ijk} + D^{kij} + D^{jki} &= E^{ijk}-E^{jik} + E^{kij}-E^{ikj} + E^{jki}-E^{kji} \\
&= E^{ijk}-E^{jik} + E^{kji}-E^{ijk} + E^{jik}-E^{kji} = 0.
\end{split}
\]
\end{note}

\begin{lemma}\label{ev u}
The following evolution equations hold:
\begin{align*}
\partial_tP^{mn}
=&-g^{mn}\det P-HP^{mn}+\frac{1}{4}P^{mn}T^k\nabla_ku\\
&-\frac{1}{4}T^mT^n+\frac{1}{2}P^{mn}\Box u-\frac{1}{2}P^{mk}P^{nl}\nabla^2_{k,l}u\\
&+\nabla_kD^{knm}+\frac{1}{2}D^{kmn}\nabla_ku,
\end{align*}
\begin{align*}
\partial_t u=&\Box u+\frac{1}{2}\left(\left|D^{ijk}\right|^2_V+\left|T^i\right|_V^2\right)-2H.
\end{align*}
\end{lemma}
\begin{proof}
The evolution equation of the Riemann curvature tensor is given by the standard formula
\begin{align*}
\partial_t R_{ijkl}=&\nabla^2_{i,l}h_{jk}+\nabla^2_{j,k}h_{il}-\nabla^2_{i,k}h_{jl}-\nabla^2_{j,l}h_{ik}\\
&+g^{pq}(R_{ijpk}h_{ql}+R_{ijpl}h_{qk}).
\end{align*}
On the other hand, the evolution of the volume form is given by $$\partial_t\mu_{ijk}=H\mu_{ijk},\quad\partial_t\mu^{ijk}=-H\mu^{ijk}.$$
Since $P^{mn}=-\frac{1}{4}\mu^{ijm}\mu^{kln}R_{ijkl}$, we obtain
\begin{align*}
\partial_tP^{mn}=&\mu^{ijm}\mu^{kln}\nabla^2_{i,k}h_{jl}-\frac{1}{2}\mu^{ijm}\mu^{kln}g^{pq}R_{ijpl}h_{qk}-2HP^{mn}.
\end{align*}
Now using the identity
\[\frac{1}{2}\mu^{ijm}\mu^{kln}g^{pq}R_{ijpl}h_{qk}+HP^{mn}=g^{mn}\det P,\]
we arrive at
\begin{align*}
\partial_tP^{mn}=&\nabla^2_{k,l}(P^{kl}P^{mn}-P^{km}P^{ln})-g^{mn}\det P-HP^{mn}\\
=&\nabla_k(P^{kl}\nabla_lP^{nm}-P^{nl}\nabla_lP^{km})-g^{mn}\det P-HP^{mn}\\
=&\nabla_k\left(T^{knm}-T^{nkm}\right)-g^{mn}\det P-HP^{mn}\\
=&\nabla_kD^{knm}+\frac{1}{2}\nabla_k\left(P^{nm}T^k-P^{mk}T^n\right)-g^{mn}\det P-HP^{mn}\\
=&\nabla_kD^{knm}-g^{mn}\det P-HP^{mn}+\frac{1}{2}P^{mn}\Box u\\
&+\frac{1}{2}\left(T^{kmn}-T^{mkn}\right)\nabla_ku-\frac{1}{2}P^{mk}P^{nl}\nabla^2_{k,l}u\\
=&\nabla_kD^{knm}+\frac{1}{2}D^{kmn}\nabla_ku-g^{mn}\det P-HP^{mn}+\frac{1}{2}P^{mn}\Box u\\
&+\frac{1}{4}\left(P^{mn}T^k-P^{nk}T^m\right)\nabla_ku-\frac{1}{2}P^{mk}P^{nl}\nabla^2_{k,l}u.
\end{align*}
The second evolution equation follows from \cite[Prop. 9]{MR2055396} and  \cite[Equ. (4)]{MR2055396}.
\end{proof}
\begin{lemma}
\begin{align*}
\frac{1}{2}\Box P^{ij}\nabla_iu\nabla_ju=&\frac{1}{2}\nabla_kP^{mi}\nabla_mP^{kj}\nabla_iu\nabla_ju-\frac{1}{2}T^m{{R_{km}}^k}_nP^{ni}\nabla_iu-\frac{1}{2}T^m{{R_{km}}^i}_nP^{kn}\nabla_iu\\
&+\frac{1}{4}T^i\Box u\nabla_iu-\frac{1}{4}T^iT^j\nabla^2_{i,j}u+\frac{1}{2}\nabla_k D^{kij}\nabla_iu\nabla_ju.
\end{align*}
\end{lemma}
\begin{proof}
\begin{align*}
\Box P^{ij}\nabla_iu\nabla_ju=&\nabla_kT^{kij}\nabla_iu\nabla_ju\\
=&\nabla_kT^{ikj}\nabla_iu\nabla_ju+\nabla_k D^{kij}\nabla_iu\nabla_ju+\frac{1}{2}\nabla_k\left(P^{ij}T^k-P^{jk}T^i\right)\nabla_iu\nabla_ju\\
=&\nabla_k(P^{im}\nabla_mP^{kj})\nabla_iu\nabla_ju+\nabla_k D^{kij}\nabla_iu\nabla_ju+\frac{1}{2}T^i\Box u\nabla_iu-\frac{1}{2}T^iT^j\nabla^2_{i,j}u\\
=&\nabla_kP^{im}\nabla_mP^{kj}\nabla_iu\nabla_ju+T^m\nabla^2_{k,m}P^{ki}\nabla_iu+\frac{1}{2}T^i\Box u\nabla_iu\\
&-\frac{1}{2}T^iT^j\nabla^2_{i,j}u+\nabla_k D^{kij}\nabla_iu\nabla_ju\\
=&\nabla_kP^{im}\nabla_mP^{kj}\nabla_iu\nabla_ju-T^m{{R_{km}}^k}_nP^{ni}\nabla_iu-T^m{{R_{km}}^i}_nP^{kn}\nabla_iu\\
&+\frac{1}{2}T^i\Box u\nabla_iu-\frac{1}{2}T^iT^j\nabla^2_{i,j}u+\nabla_k D^{kij}\nabla_iu\nabla_ju.
\end{align*}
\end{proof}
\begin{lemma}
\begin{align*}
\frac{1}{2}\Box\left(P^{ij}\nabla_i u\nabla_ju\right)=&\frac{1}{2}\Box P^{ij}\nabla_i u\nabla_ju+2T^{ijk}\nabla^2_{i,j}u\nabla_ku\\
&+T^i\Box\nabla_i u+P^{kl}P^{ij}\nabla^2_{l,i}u\nabla^2_{k,j}u.
\end{align*}
\end{lemma}
\begin{proof}
\begin{align*}
\Box\left(P^{ij}\nabla_i u\nabla_ju\right)=&P^{kl}\nabla_k\left(\nabla_lP^{ij}\nabla_iu\nabla_ju+2P^{ij}\nabla^2_{l,i}u\nabla_ju\right)\\
=&\Box P^{ij}\nabla_i u\nabla_ju+2T^{kij}\nabla^2_{k,i}u\nabla_ju\\
&+2T^{lij}\nabla^2_{l,i}u\nabla_ju+2T^i\Box\nabla_i u+2P^{kl}P^{ij}\nabla^2_{l,i}u\nabla^2_{k,j}u.
\end{align*}
\end{proof}
\begin{lemma}
\begin{align*}
(\partial_t \Box-\Box\partial_t) u=
&-\det P\Delta u-H\Box u+\frac{1}{4}T^i\nabla_iu\Box u-\frac{1}{4}T^iT^j\nabla^2_{i,j}u\\
&+\frac{1}{2}(\Box u)^2-\frac{1}{2}P^{ik}P^{jl}\nabla^2_{k,l}u\nabla^2_{i,j}u\\
&+\left(\nabla_kD^{knm}+\frac{1}{2}D^{kmn}\nabla_ku\right)\nabla^2_{m,n}u.
\end{align*}
\end{lemma}
\begin{proof}
\begin{align*}
(\partial_t \Box-\Box \partial_t)u
=&\partial_tP^{ij}\nabla^2_{i,j}u-P^{ij}\partial_t\Gamma_{ij}^k\nabla_ku.
\end{align*}
A calculation shows that the time derivative of the Christoffel symbols is given by
\begin{align*}
\partial_t \Gamma_{ij}^k&=g^{kl}\left(\nabla_ih_{jl}+\nabla_jh_{il}-\nabla_{l}h_{ij}\right).
\end{align*}
Thus using identity (\ref{equ: important}) we calculate
\begin{align*}
P^{ij}\partial_t \Gamma_{ij}^k=&g^{kl}\left(P^{ij}\nabla_ih_{jl}+P^{ij}\nabla_jh_{il}-P^{ij}\nabla_{l}h_{ij}\right)\\
=&g^{kl}\left(\frac{1}{2}P^{ij}\nabla_lh_{ij}+\frac{1}{2}P^{ij}\nabla_lh_{ij}-P^{ij}\nabla_{l}h_{ij}\right)=0.
\end{align*}
Hence the claim follows from Lemma \ref{ev u}.
\end{proof}
\begin{lemma}
\begin{align*}
-2\partial_tH&=2\|h\|^2+2H^2-\frac{1}{2}HT^i\nabla_iu
\\&-\frac{1}{2}\det P |\nabla u|^2
-H\Box u-\det P\Delta u\\
&+2\left(\nabla_kD^{knm}+\frac{1}{2}D^{kmn}\nabla_ku\right)h_m^lV_{ln}
-H\left|D^{ijk}\right|_V^2.
\end{align*}
\end{lemma}
\begin{proof}
\begin{align*}
\partial_tH=&\partial_t(V\det P)\\
=&\det P\partial_t V+H\partial_tu\\
=&\det P(-2h^{ij}V_{ij}-g^{ij}V_{im}V_{jn}\partial_tP^{mn})+H\partial_tu\\
=&-2\|h\|^2+H\partial_tu-h_m^lV_{ln}\partial_tP^{mn}\\
=&-2\|h\|^2+H\left(\Box u-2H+\frac{1}{2}\left(\left|D^{ijk}\right|^2_V+\left|T^i\right|_V^2\right)\right)\\
&-\left(\nabla_kD^{knm}+\frac{1}{2}D^{kmn}\nabla_ku\right)h_m^lV_{ln}+\|h\|^2+H^2\\
&-\frac{1}{4}HT^k\nabla_ku+\frac{1}{4}T^mT^nh_m^lV_{ln}-\frac{1}{2}H\Box u+\frac{1}{2}\det P\Delta u.
\end{align*}
To complete the proof, note that
\[T^iT^jh_i^lV_{lj}=\det P|\nabla u|^2.\]
\end{proof}
\begin{lemma}
\[\Box\left|D^{ijk}\right|^2_V=\cdots\]
\end{lemma}
\begin{lemma}
\[\partial_t\left|D^{ijk}\right|^2_V=\Box\left|D^{ijk}\right|^2_V+\cdots\]
\end{lemma}

* The Harnack Inequality                                           :noexport:

Let us define
\begin{align*}
w_{kl}:=&\nabla^2_{k,l}u+V_{lm}\nabla_kP^{mn}\nabla_nu-2h_k^mV_{ml},\\
w:=&\Box u-2H=\partial_tu-\frac{1}{2}\left(\left|D^{ijk}\right|^2_V+\left|T^i\right|_V^2\right).
\end{align*}
Note that we have
\begin{align*}
(\partial_t-\Box)w
&= \frac{1}{2}\Box\left|D^{ijk}\right|^2_V+\frac{1}{2}\Box\left|T^i\right|_V^2+(\partial_t \Box-\Box\partial_t) u-2\partial_tH.
\end{align*}
\begin{lemma}
\begin{align*}
(\partial_t-\Box)w&=P^{ij}\nabla_i u\nabla_j w+ \frac{1}{2}\left(P^{ik}P^{jl}w_{ij}w_{kl}+w^2\right)+f(D^{ijk}).\\
\end{align*}
\end{lemma}
\begin{proof}
We start by multiplying
\begin{align*}
w_{ij}&=\nabla^2_{i,j}u+V_{jr}\nabla_iP^{rs}\nabla_su-2h_i^rV_{rj},\\
w_{kl}&=\nabla^2_{k,l}u+V_{lm}\nabla_kP^{mn}\nabla_nu-2h_k^mV_{ml}.
\end{align*}
We have
\begin{align*}
P^{ik}P^{jl}w_{ij}w_{kl}=&P^{ik}P^{jl}\nabla^2_{i,j}u\nabla^2_{k,l}u+2P^{ik}P^{jl}V_{lm}\nabla_kP^{mn}\nabla_nu\nabla^2_{i,j}u\\
&-4P^{ik}P^{jl}h_k^mV_{ml}\nabla^2_{i,j}u+P^{ik}P^{jl}V_{jr}V_{lm}\nabla_iP^{rs}\nabla_kP^{mn}\nabla_su\nabla_nu\\
&-4P^{ik}P^{jl}V_{jr}h_k^mV_{ml}\nabla_iP^{rs}\nabla_su+4P^{ik}P^{jl}h_i^rV_{rj}h_k^mV_{ml}\\
=&P^{ik}P^{jl}\nabla^2_{i,j}u\nabla^2_{k,l}u+2P^{ik}\nabla_kP^{nj}\nabla_nu\nabla^2_{i,j}u-4\det P g^{ij}\nabla^2_{i,j}u\\
&+P^{ik}V_{jr}\nabla_iP^{rs}\nabla_kP^{jn}\nabla_su\nabla_nu-4h^i_r\nabla_iP^{rs}\nabla_su+4\|h\|^2\\
=&P^{ik}P^{jl}\nabla^2_{i,j}u\nabla^2_{k,l}u+ {2T^{ijk}\nabla^2_{i,j}u\nabla_ku}-4\det P \Delta u\\
&+T^{ijk}V_{jr}\nabla_iP^{rs}\nabla_su\nabla_ku-4h_{j}^i\nabla_iP^{jk}\nabla_ku+ {4\|h\|^2}\\
=&P^{ik}P^{jl}\nabla^2_{i,j}u\nabla^2_{k,l}u+ {2T^{ijk}\nabla^2_{i,j}u\nabla_ku}-4\det P \Delta u-4h_{j}^i\nabla_iP^{jk}\nabla_ku\\
&+ {4\|h\|^2}+T^{jik}V_{jr}\nabla_iP^{rs}\nabla_su\nabla_ku+D^{ijk}V_{jr}\nabla_iP^{rs}\nabla_su\nabla_ku\\
&+\frac{1}{2}\left(P^{jk}T^i-P^{ik}T^j\right)V_{jr}\nabla_iP^{rs}\nabla_su\nabla_ku.
\end{align*}
Therefore,
\begin{align*}
\frac{1}{2}P^{ik}P^{jl}w_{ij}w_{kl}=&\frac{1}{2}P^{ik}P^{jl}\nabla^2_{i,j}u\nabla^2_{k,l}u+ {T^{ijk}\nabla^2_{i,j}u\nabla_ku}-2\det P \Delta u-2h_{j}^i\nabla_iP^{jk}\nabla_ku\\
&+ {2\|h\|^2}+\frac{1}{2}\nabla_mP^{ik}\nabla_iP^{ms}\nabla_su\nabla_ku+\frac{1}{2}D^{ijk}V_{jr}\nabla_iP^{rs}\nabla_su\nabla_ku.
\end{align*}
We also have
\begin{align*}
\frac{1}{2}w^2=& {\frac{1}{2}(\Box u)^2-2H\Box u}+ {2H^2}.
\end{align*}
Next we calculate
\begin{align*}
\nabla_k w=&\nabla_k\Box u-2g^{ij}\nabla_k(V_{ij}\det P)\\
=&\nabla_k(P^{ij}\nabla^2_{i,j} u)+2h_i^mV_{mj}\nabla_kP^{ij}-2H\nabla_ku\\
=&\nabla_kP^{ij}\nabla^2_{i,j}u+2h_k^i\nabla_iu+\Box\nabla_ku+2h_i^mV_{mj}\nabla_kP^{ij}-2H\nabla_ku.
\end{align*}
Therefore, we obtain
\begin{align*}
P^{kl}\nabla_k w\nabla_lu
=&P^{kl}\nabla_kP^{ij}\nabla_lu\nabla^2_{i,j}u+2\det P|\nabla u|^2+P^{kl}\Box\nabla_ku\nabla_lu\\
&+2h_i^mV_{mj}P^{kl}\nabla_kP^{ij}\nabla_lu-2HP^{kl}\nabla_ku\nabla_lu\\
=&T^{lij}\nabla^2_{i,j}u\nabla_lu+2\det P|\nabla u|^2+T^{k}\Box\nabla_ku\\
&+2h_i^mV_{mj}T^{lij}\nabla_lu-2HT^{k}\nabla_ku\\
=& {T^{ilj}\nabla^2_{i,j}u\nabla_lu}+\left(D^{lij}+\frac{1}{2}\left(P^{ij}T^l-P^{lj}T^i\right)\right)\nabla^2_{i,j}u\nabla_lu\\
&+2\det P|\nabla u|^2+ {T^{k}\Box\nabla_ku}+2h_i^mV_{mj}T^{lij}\nabla_lu-2HT^{k}\nabla_ku\\
=& {T^{ijl}\nabla^2_{i,j}u\nabla_lu}+\frac{1}{2}T^l\Box u\nabla_lu-\frac{1}{2}T^iT^j\nabla^2_{i,j}u+2\det P|\nabla u|^2\\
&+{T^{k}\Box\nabla_ku}+2h_i^kV_{kj}T^{lij}\nabla_lu-2HT^{k}\nabla_ku+D^{lij}\nabla^2_{i,j}u\nabla_lu\\
=&{T^{ijl}\nabla^2_{i,j}u\nabla_lu}+\frac{1}{2}T^l\Box u\nabla_lu-\frac{1}{2}T^iT^j\nabla^2_{i,j}u+2\det P|\nabla u|^2\\
&+{T^{k}\Box\nabla_ku}+2h_i^kV_{kj}T^{ijl}\nabla_lu-2HT^{k}\nabla_ku+D^{lij}\nabla^2_{i,j}u\nabla_lu\\
&+2h_i^kV_{kj}D^{lij}\nabla_lu+h_i^kV_{kj}(P^{ij}T^l-P^{jl}T^i)\nabla_lu\\
=&{T^{ijk}\nabla^2_{i,j}u\nabla_ku}+\frac{1}{2}T^i\Box u\nabla_iu-\frac{1}{2}T^iT^j\nabla^2_{i,j}u+\det P|\nabla u|^2\\
&+{T^i\Box\nabla_iu}+2h_{j}^i\nabla_iP^{jk}\nabla_ku-HT^{i}\nabla_iu+\left(2h_i^kV_{kj}+\nabla^2_{i,j}u\right)D^{lij}\nabla_lu.
\end{align*}

\begin{align*}
\nabla^2_{i,j}u+V_{ac}V_{bd}\nabla_iP^{cd}\nabla_jP^{ab}=& V_{ab}\nabla^2_{i,j}P^{ab},\\
\nabla_iu&\leftrightarrow V_{ab}\nabla_iP^{ab}.
\end{align*}

\begin{align*}
\nabla_s z=&\nabla_s\left(\left(P^{kl}\nabla_l P^{ij}-P^{jl}\nabla_lP^{ik}\right)V_{im}V_{jn}\nabla_kP^{mn}\right)\\
=&V_{im}V_{jn}\nabla_kP^{mn}\nabla_s P^{kl}\nabla_l P^{ij}\\
&+P^{kl}V_{im}V_{jn}\nabla_kP^{mn}\nabla^2_{s,l} P^{ij}\\
&-V_{im}V_{jn}\nabla_kP^{mn}\nabla_sP^{jl}\nabla_lP^{ik}\\
&-P^{jl}V_{im}V_{jn}\nabla_kP^{mn}\nabla^2_{s,l}P^{ik}\\
&-V_{ip}V_{mq}V_{jn}P^{kl}\nabla_sP^{pq}\nabla_l P^{ij}\nabla_kP^{mn}\\
&-V_{im}V_{jp}V_{nq}P^{kl}\nabla_sP^{pq}\nabla_l P^{ij}\nabla_kP^{mn}\\
&+V_{im}V_{jn}P^{kl}\nabla_l P^{ij}\nabla^2_{s,k}P^{mn}\\
&+V_{ip}V_{mq}V_{jn}P^{jl}\nabla_sP^{pq}\nabla_lP^{ik}\nabla_kP^{mn}\\
&+V_{im}V_{jp}V_{nq}P^{jl}\nabla_sP^{pq}\nabla_lP^{ik}\nabla_kP^{mn}\\
&-V_{im}V_{jn}P^{jl}\nabla_lP^{ik}\nabla^2_{s,k}P^{mn}\\
=&V_{im}V_{jn}\nabla_kP^{mn}\nabla_s P^{kl}\nabla_l P^{ij}\\
&+P^{kl}V_{im}V_{jn}\nabla_kP^{mn}\nabla^2_{s,l} P^{ij}\\
&-V_{im}V_{jn}\nabla_kP^{mn}\nabla_sP^{jl}\nabla_lP^{ik}\\
&-V_{im}\nabla_kP^{ml}\nabla^2_{s,l}P^{ik}\\
&-V_{ip}V_{mq}V_{jn}P^{kl}\nabla_sP^{pq}\nabla_l P^{ij}\nabla_kP^{mn}\\
&-V_{im}V_{jp}V_{nq}P^{kl}\nabla_sP^{pq}\nabla_l P^{ij}\nabla_kP^{mn}\\
&+V_{im}V_{jn}P^{kl}\nabla_l P^{ij}\nabla^2_{s,k}P^{mn}\\
&+V_{ip}V_{mq}\nabla_sP^{pq}\nabla_lP^{ik}\nabla_kP^{ml}\\
&+V_{im}V_{nq}\nabla_sP^{lq}\nabla_lP^{ik}\nabla_kP^{mn}\\
&-V_{im}\nabla_lP^{ik}\nabla^2_{s,k}P^{ml}.
\end{align*}
Therefore
\begin{align*}
&\nabla^2_{r,s} z\\
=&-V_{ia}V_{mb}V_{jn}\nabla_r P^{ab}\nabla_kP^{mn}\nabla_s P^{kl}\nabla_l P^{ij}-V_{ja}V_{nb}V_{im}\nabla_r P^{ab}\nabla_kP^{mn}\nabla_s P^{kl}\nabla_l P^{ij}\\
&+V_{im}V_{jn}\nabla^2_{r,k}P^{mn}\nabla_s P^{kl}\nabla_l P^{ij}+V_{im}V_{jn}\nabla_kP^{mn}\nabla^2_{r,s} P^{kl}\nabla_l P^{ij}\\
&+V_{im}V_{jn}\nabla_kP^{mn}\nabla_s P^{kl}\nabla^2_{r,l} P^{ij}-V_{ia}V_{mb}V_{jn}P^{kl}\nabla_rP^{ab}\nabla_kP^{mn}\nabla^2_{s,l} P^{ij}\\
&-V_{ja}V_{nb}V_{im}P^{kl}\nabla_rP^{ab}\nabla_kP^{mn}\nabla^2_{s,l} P^{ij}+V_{im}V_{jn}\nabla_rP^{kl}\nabla_kP^{mn}\nabla^2_{s,l} P^{ij}\\
&+V_{im}V_{jn}P^{kl}\nabla^2_{r,k}P^{mn}\nabla^2_{s,l} P^{ij}+V_{im}V_{jn}P^{kl}\nabla_kP^{mn}\nabla_r\nabla^2_{s,l} P^{ij}\\
&+V_{ia}V_{mb}V_{jn}\nabla_rP^{ab}\nabla_kP^{mn}\nabla_sP^{jl}\nabla_lP^{ik}\\
&+V_{ja}V_{nb}V_{im}\nabla_rP^{ab}\nabla_kP^{mn}\nabla_sP^{jl}\nabla_lP^{ik}-V_{im}V_{jn}\nabla^2_{r,k}P^{mn}\nabla_sP^{jl}\nabla_lP^{ik}\\
&-V_{im}V_{jn}\nabla_kP^{mn}\nabla^2_{r,s}P^{jl}\nabla_lP^{ik}-V_{im}V_{jn}\nabla_kP^{mn}\nabla_sP^{jl}\nabla^2_{r,l}P^{ik}\\
&+V_{ia}V_{mb}\nabla_rP^{ab}\nabla_kP^{ml}\nabla^2_{s,l}P^{ik}-V_{im}\nabla^2_{r,k}P^{ml}\nabla^2_{s,l}P^{ik}\\
&-V_{im}\nabla_kP^{ml}\nabla_r\nabla^2_{s,l}P^{ik}+V_{ia}V_{pb}V_{mq}V_{jn}P^{kl}\nabla_rP^{ab}\nabla_sP^{pq}\nabla_l P^{ij}\nabla_kP^{mn}\\
&+V_{ma}V_{qb}V_{ip}V_{jn}P^{kl}\nabla_rP^{ab}\nabla_sP^{pq}\nabla_l P^{ij}\nabla_kP^{mn}+V_{ja}V_{nb}V_{mq}V_{ip}P^{kl}\nabla_rP^{ab}\nabla_sP^{pq}\nabla_l P^{ij}\nabla_kP^{mn}\\
&-V_{ip}V_{mq}V_{jn}\nabla_rP^{kl}\nabla_sP^{pq}\nabla_l P^{ij}\nabla_kP^{mn}-V_{ip}V_{mq}V_{jn}P^{kl}\nabla^2_{r,s}P^{pq}\nabla_l P^{ij}\nabla_kP^{mn}\\
&-V_{ip}V_{mq}V_{jn}P^{kl}\nabla_sP^{pq}\nabla^2_{r,l} P^{ij}\nabla_kP^{mn}-V_{ip}V_{mq}V_{jn}P^{kl}\nabla_sP^{pq}\nabla_l P^{ij}\nabla^2_{r,k}P^{mn}\\
&+V_{ia}V_{mb}V_{jp}V_{nq}P^{kl}\nabla_rP^{ab}\nabla_sP^{pq}\nabla_l P^{ij}\nabla_kP^{mn}+V_{ja}V_{pb}V_{im}V_{nq}P^{kl}\nabla_rP^{ab}\nabla_sP^{pq}\nabla_l P^{ij}\nabla_kP^{mn}\\
&+V_{na}V_{qb}V_{im}V_{jp}P^{kl}\nabla_rP^{ab}\nabla_sP^{pq}\nabla_l P^{ij}\nabla_kP^{mn}-V_{im}V_{jp}V_{nq}\nabla_rP^{kl}\nabla_sP^{pq}\nabla_l P^{ij}\nabla_kP^{mn}\\
&-V_{im}V_{jp}V_{nq}P^{kl}\nabla^2_{r,s}P^{pq}\nabla_l P^{ij}\nabla_kP^{mn}-V_{im}V_{jp}V_{nq}P^{kl}\nabla_sP^{pq}\nabla^2_{r,l} P^{ij}\nabla_kP^{mn}\\
&-V_{im}V_{jp}V_{nq}P^{kl}\nabla_sP^{pq}\nabla_l P^{ij}\nabla^2_{r,k}P^{mn}-V_{ia}V_{mb}V_{jn}P^{kl}\nabla_rP^{ab}\nabla_l P^{ij}\nabla^2_{s,k}P^{mn}\\
&-V_{ja}V_{nb}V_{im}P^{kl}\nabla_rP^{ab}\nabla_l P^{ij}\nabla^2_{s,k}P^{mn}+V_{im}V_{jn}P^{kl}\nabla^2_{r,l} P^{ij}\nabla^2_{s,k}P^{mn}\\
&+V_{im}V_{jn}P^{kl}\nabla_l P^{ij}\nabla_r\nabla^2_{s,k}P^{mn}-V_{ia}V_{pb}V_{mq}\nabla_rP^{ab}\nabla_sP^{pq}\nabla_lP^{ik}\nabla_kP^{ml}\\
&-V_{ip}V_{ma}V_{mb}\nabla_rP^{ab}\nabla_sP^{pq}\nabla_lP^{ik}\nabla_kP^{ml}+V_{ip}V_{mq}\nabla^2_{r,s}P^{pq}\nabla_lP^{ik}\nabla_kP^{ml}\\
&+V_{ip}V_{mq}\nabla_sP^{pq}\nabla^2_{r,l}P^{ik}\nabla_kP^{ml}+V_{ip}V_{mq}\nabla_sP^{pq}\nabla_lP^{ik}\nabla^2_{r,k}P^{ml}\\
&-V_{ia}V_{mb}V_{nq}\nabla_rP^{ab}\nabla_sP^{lq}\nabla_lP^{ik}\nabla_kP^{mn}-V_{na}V_{qb}V_{im}\nabla_rP^{ab}\nabla_sP^{lq}\nabla_lP^{ik}\nabla_kP^{mn}\\
&+V_{im}V_{nq}\nabla^2_{r,s}P^{lq}\nabla_lP^{ik}\nabla_kP^{mn}+V_{im}V_{nq}\nabla_sP^{lq}\nabla^2_{r,l}P^{ik}\nabla_kP^{mn}+V_{im}V_{nq}\nabla_sP^{lq}\nabla_lP^{ik}\nabla^2_{r,k}P^{mn}\\
&+V_{ia}V_{mb}\nabla_rP^{ab}\nabla_lP^{ik}\nabla^2_{s,k}P^{ml}-V_{im}\nabla^2_{r,l}P^{ik}\nabla^2_{s,k}P^{ml}-V_{im}\nabla_lP^{ik}\nabla_r\nabla^2_{s,k}P^{ml}.
\end{align*}
\end{proof}
